# Generated by Django 5.0 on 2024-05-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userstate_delete_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='userstate',
        ),
    ]
