# Generated by Django 5.0 on 2024-05-10 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userstate_user_delete_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=40, null=True)),
                ('lastname', models.CharField(blank=True, max_length=40, null=True)),
                ('avatar', models.ImageField(upload_to=None)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='userstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('allergies', models.CharField(max_length=50)),
                ('activity_level', models.FloatField()),
                ('Work_Out_Level', models.CharField(choices=[('intermediate', 'intermediate'), ('Beginner', 'Beginner'), ('Advanced', 'Advanced')], max_length=50)),
                ('fitness_goals', models.CharField(choices=[('Gain weight', 'Gain weight'), ('Healthy Lifestyle', 'Healthy Lifestyle'), ('Lose Weight', 'Lose Weight')], max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
