# Generated by Django 5.0 on 2024-05-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_userstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userstate',
        ),
    ]
