# Generated by Django 5.0 on 2024-06-06 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_genai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genai',
            name='data',
            field=models.CharField(blank=True, max_length=7000, null=True),
        ),
        migrations.AlterField(
            model_name='genai',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
