# Generated by Django 5.0 on 2024-06-07 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_firstname_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genai',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GenAI', to=settings.AUTH_USER_MODEL),
        ),
    ]
