# Generated by Django 5.0 on 2024-06-07 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_genai_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='wGenAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workGenAI', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
