# Generated by Django 5.0 on 2024-06-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_userstate_work_out_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstate',
            name='Work_Out_Level',
            field=models.CharField(choices=[('Intermediate', 'Intermediate'), ('Beginner', 'Beginner'), ('Advanced', 'Advanced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='fitness_goals',
            field=models.CharField(choices=[('Gain Weight', 'Gain Weight'), ('Healthy Lifestyle', 'Healthy Lifestyle'), ('Lose Weight', 'Lose Weight')], max_length=50),
        ),
    ]
