# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app/

# Install the dependencies from requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Set environment variables
ENV REDIS_URL="redis://default:UfCtuNkTPpVOAirpBzrMrmdVFeFczzmA@junction.proxy.rlwy.net:39781/0"
ENV DJANGO_SECRET_KEY="django-insecure-$%vmmb2fkkw4z3+3(r3azueo*30g1t(g)qxnrnh2ll%jqpdq7d"

# Make migrations
RUN python manage.py migrate

# Install Celery
RUN pip install celery

# Expose the port for Django application
EXPOSE 8000

# Start Django, Celery worker, and Celery Beat services
CMD bash -c "python manage.py runserver 0.0.0.0:8000 & \
  celery -A graduation worker --loglevel=info --solo & \
  celery -A graduation beat --loglevel=info"
